Add support for ppc64le
upbound/build pull request #134
Opened 2021-02-05 17:42 UTC by amitsadaphule

Crossplane build and tests have been validated on ppc64le with these changes.

2021-05-20 17:41 UTC, negz commented
@AaronME would you mind taking a look at this PR, since you recently did a bunch of work with architecture support? I'm happy to merge if it looks good to you.

2021-05-20 18:22 UTC, AaronME requested changes
LGTM, minor notes.

2021-05-21 04:05 UTC, negz commented
Thanks @AaronME! @amitsadaphule let me know when this is ready to merge.

2021-05-21 06:15 UTC, amitsadaphule commented on makelib/common.mk
>  $(error build only supported on amd64 and arm64 host currently)
Right, missed that. I'll add that.

2021-05-21 06:16 UTC, amitsadaphule commented on makelib/common.mk
> +
OK, thanks for the pointer! :) I'll remove this and add in the main project being compiled.

2021-05-21 15:37 UTC, amitsadaphule commented on makelib/common.mk
>  $(error build only supported on amd64 and arm64 host currently)
Done.

2021-05-21 15:37 UTC, amitsadaphule commented on makelib/common.mk
> +
Done.

2021-05-21 15:38 UTC, amitsadaphule commented
@negz I've incorporated the review comments and validated the changes locally. Ready to merge! :) Thanks!

2021-05-25 06:34 UTC, amitsadaphule commented
@negz @AaronME please review.

2021-05-25 15:45 UTC, AaronME approved these changes
LGTM!

Crossplane builds successfullly on mac m1 and intel processors.

2021-05-25 16:48 UTC, merged

2021-05-25 16:48 UTC, negz commented
Thanks for adding this functionality @amitsadaphule!