Remove docs publishing and version-specific changes
upbound/build pull request #225
Opened 2022-12-16 22:08 UTC by plumbis

### Description of your changes
This removes `docs.publish` and all version related actions for docs. 

This is related to crossplane/crossplane issue [#3461](https://github.com/crossplane/crossplane/issues/3461), moving the docs out of the crossplane/crossplane repo. 

Other docs make options are left in case a crossplane developer need to build docs locally for some reason. 

Signed-off-by: Pete Lumbis <pete@upbound.io>

2022-12-16 22:12 UTC, hasheddan requested changes
@plumbis if this is the direction we end up going I think we can do it without ripping out this generic functionality (i.e. make it so crossplane doesn't publish docs rather than make it so that the build submodule can't publish docs).

2022-12-16 22:22 UTC, plumbis commented
This method was to split the difference and still enable local docs builds/previews from crossplane (see Crossplane [PR #3538](https://github.com/crossplane/crossplane/pull/3538)) 

If we want to remove all docs related things from Crossplane then I'm fine with closing this.

2022-12-17 13:01 UTC, hasheddan commented
> This method was to split the difference and still enable local docs builds/previews from crossplane

@plumbis my point is that this PR is removing common functionality. If Crossplane wants to do local builds and previews, but _not_ publish, we should enable that in this module, rather than removing the ability to publish altogether.

2022-12-28 16:06 UTC, plumbis commented
Thanks Dan. I'll close this and make changes to the Makefiles in the other repos.

2022-12-28 16:06 UTC, closed without merging